default_language_version:
  python: python3
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/google/yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    name: yapf
    description: A formatter for Python files.
    entry: yapf
    args: [-i, -vv, -p]  # inplace
    language: python
    types: [python]
    additional_dependencies:
    - toml
- repo: https://github.com/pycqa/isort
  hooks:
  - id: isort
  rev: 5.12.0
