name: run-tests
on: [push]
jobs:
  linear_tests:
    runs-on: [self-hosted]
    steps:
    - name: Correctness tests
    - uses: actions/checkout@v3
      run: |
        echo 'Setup...'
        python setup.py install --prefix ~/.local
        echo 'Run tests...'

        python ./megablocks/ops/sort_test.py
        python ./megablocks/ops/padded_scatter_test.py
        python ./megablocks/ops/replicate_test.py
        python ./megablocks/ops/histogram_test.py
        python ./megablocks/ops/cumsum_test.py
        python ./megablocks/ops/padded_gather_test.py
        python ./megablocks/ops/binned_gather_test.py
        python ./megablocks/ops/binned_scatter_test.py
        python ./megablocks/ops/topology_test.py
        python ./megablocks/layers/dmoe_test.py
        python ./megablocks/layers/memory_test.py
        python ./megablocks/layers/glu_test.py
        python ./megablocks/layers/parallelism_test.py
        python ./megablocks/layers/moe_test.py
